[test]
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
preload = ["./src/rules/bunpro/_test/preload.ts"]

=======
preload = "./packages/grammar/src/rules/bunpro/_test/preload.ts"
>>>>>>> jlpt3-tatoe-temo
=======
preload = ["./packages/grammar/src/rules/bunpro/_test/preload.ts"]
>>>>>>> jlpt3-tatotan
=======
preload = ["./packages/grammar/src/rules/bunpro/_test/preload.ts"]
>>>>>>> jlpt3-zuni
