import type { PresentationCatalog } from '../schema.js';

export const EN_CATALOG = {
  ui: {
    home: 'Ichiran home', settings: 'Analyzer settings', analyzerData: 'Analyzer data',
    interfaceLanguage: 'Interface', onThisDevice: '{size} on this device', removeData: 'Remove data',
    licenses: 'Licenses', installTitle: 'Install Japanese data',
    installIntro: 'Download once. Analysis reads this data directly from your device.',
    preparing: 'Preparing analyzer', staleData: 'Your local data needs an update.',
    incompleteData: 'The saved data is incomplete. Install it again.',
    insufficientStorage: 'There is not enough free storage for the analyzer.',
    clearFailed: 'The saved data could not be removed.', downloadFailed: 'The download did not finish.',
    downloading: 'Downloading', checkingFiles: 'Checking files', savingDevice: 'Saving to this device',
    openingAnalyzer: 'Opening analyzer', reinstall: 'Reinstall analyzer data', retry: 'Retry',
    install: 'Install analyzer data', download: 'Download', stored: 'Stored', byteProgress: '{received} of {total}',
    privacy: 'Your text stays on this device.', examples: 'Examples', trySentence: 'Try a sentence',
    reading: 'reading {reading}', word: 'word', detailsFailed: 'Word details could not be opened.',
    romanizationFailed: 'Romanization could not be generated.',
    replaceFailed: 'The new data could not replace the current copy.', japaneseText: 'Japanese text',
    composerIntro: 'Paste a sentence or choose an example.', clearJapanese: 'Clear Japanese text',
    analyzing: 'Analyzing', analyze: 'Analyze', analysisFailed: 'Analysis failed.', tryAgain: 'Try again',
    analysisResult: 'Analysis result', analysis: 'Analysis', definitions: 'Definitions', english: 'English',
    simplifiedChinese: 'Simplified Chinese', romanize: 'Romanize', hideRomaji: 'Hide romaji',
    otherParses: 'Other parses', analyzeHint: 'Analyze the text to see each word.',
    enterHint: 'Enter Japanese text to begin.', wordDetails: 'Word details', close: 'Close',
    copyFailed: 'The selection could not be copied.', runsOnDevice: 'Runs on this device',
    selectWord: 'Select a word', selectedText: 'Selected text', copied: 'Copied', copy: 'Copy',
    copySelected: 'Copy selected word', closeDetails: 'Close word details',
    loadingDetails: 'Loading word details', negative: 'Negative', formal: 'Formal', counter: 'Counter',
    ordinalCounter: 'Ordinal counter', properNoun: 'Proper noun', structure: 'Structure',
    conjugations: 'Conjugations', alternatives: 'Alternatives',
    unknownConjugation: 'Conjugation {type}',
    confirmRemove: 'Remove the downloaded Japanese data from this device?',
    unsupportedTitle: 'This browser cannot store the analyzer locally.',
    unsupportedIntro: 'Open Ichiran in a current browser with private browsing turned off.',
    corruptData: 'The saved data is corrupted.', reloadStatus: 'Reload to check the saved data.'
  },
  samples: {
    everyday: 'Everyday', inflection: 'Inflection', counters: 'Counters', numbers: 'Numbers',
    ambiguous: 'Ambiguous reading', mixedScripts: 'Mixed scripts', punctuation: 'Punctuation',
    colloquial: 'Colloquial', compound: 'Compound', kana: 'Kana'
  },
  pos: {
    'adj-i': 'I-Adjective', 'adj-ix': 'I-Adjective (Archaic)', 'adj-na': 'Na-Adjective',
    'adj-no': 'No-Adjective', 'adj-pn': 'Pre-noun Adjective', 'adj-t': 'Taru-Adjective',
    'adj-f': 'Prenominal', adv: 'Adverb', 'adv-to': 'To-Adverb', aux: 'Auxiliary',
    'aux-v': 'Auxiliary Verb', 'aux-adj': 'Auxiliary Adjective', conj: 'Conjunction', cop: 'Copula',
    'cop-da': 'Copula (だ)', ctr: 'Counter', exp: 'Expression', int: 'Interjection', n: 'Noun',
    'n-adv': 'Adverbial Noun', 'n-suf': 'Noun Suffix', 'n-pref': 'Noun Prefix',
    'n-t': 'Temporal Noun', 'n-pr': 'Proper Noun', num: 'Number', pn: 'Pronoun', prt: 'Particle',
    pref: 'Prefix', suf: 'Suffix', v1: 'Ichidan Verb (-ru)', 'v1-s': 'Ichidan Verb (-ru Special)',
    v5aru: 'Godan Verb (-aru)', v5b: 'Godan Verb (-bu)', v5g: 'Godan Verb (-gu)',
    v5k: 'Godan Verb (-ku)', 'v5k-s': 'Godan Verb (-ku Special)', v5m: 'Godan Verb (-mu)',
    v5n: 'Godan Verb (-nu)', v5r: 'Godan Verb (-ru)', 'v5r-i': 'Godan Verb (-ru Irregular)',
    v5s: 'Godan Verb (-su)', v5t: 'Godan Verb (-tsu)', v5u: 'Godan Verb (-u)',
    'v5u-s': 'Godan Verb (-u Special)', vk: 'Kuru Verb', vs: 'Suru Verb',
    'vs-i': 'Suru Verb (Included)', 'vs-s': 'Suru Verb (Special)', vt: 'Transitive Verb',
    vi: 'Intransitive Verb', vz: 'Zuru Verb', v5uru: 'Godan Verb (-uru)',
    'on-mim': 'Onomatopoeia', unc: 'Unclassified', 'adj-kari': 'Kari-Adjective (Archaic)',
    'adj-ku': 'Ku-Adjective (Archaic)', 'adj-shiku': 'Shiku-Adjective (Archaic)',
    'adj-nari': 'Na-Adjective (Archaic)', 'v-unspec': 'Verb (Unspecified)',
    vn: 'Nu Verb (Irregular)', vr: 'Ru Verb (Irregular)', 'vs-c': 'Su Verb (Archaic)',
    v4b: 'Yodan Verb (-bu, Archaic)', v4g: 'Yodan Verb (-gu, Archaic)',
    v4h: 'Yodan Verb (-fu, Archaic)', v4k: 'Yodan Verb (-ku, Archaic)',
    v4m: 'Yodan Verb (-mu, Archaic)', v4n: 'Yodan Verb (-nu, Archaic)',
    v4r: 'Yodan Verb (-ru, Archaic)', v4s: 'Yodan Verb (-su, Archaic)',
    v4t: 'Yodan Verb (-tsu, Archaic)', 'v2a-s': 'Nidan Verb (-u, Archaic)',
    'v2b-k': 'Upper Nidan Verb (-bu, Archaic)', 'v2b-s': 'Lower Nidan Verb (-bu, Archaic)',
    'v2d-k': 'Upper Nidan Verb (-dzu, Archaic)', 'v2d-s': 'Lower Nidan Verb (-dzu, Archaic)',
    'v2g-k': 'Upper Nidan Verb (-gu, Archaic)', 'v2g-s': 'Lower Nidan Verb (-gu, Archaic)',
    'v2h-k': 'Upper Nidan Verb (-fu, Archaic)', 'v2h-s': 'Lower Nidan Verb (-fu, Archaic)',
    'v2k-k': 'Upper Nidan Verb (-ku, Archaic)', 'v2k-s': 'Lower Nidan Verb (-ku, Archaic)',
    'v2m-k': 'Upper Nidan Verb (-mu, Archaic)', 'v2m-s': 'Lower Nidan Verb (-mu, Archaic)',
    'v2n-s': 'Lower Nidan Verb (-nu, Archaic)', 'v2r-k': 'Upper Nidan Verb (-ru, Archaic)',
    'v2r-s': 'Lower Nidan Verb (-ru, Archaic)', 'v2s-s': 'Lower Nidan Verb (-su, Archaic)',
    'v2t-k': 'Upper Nidan Verb (-tsu, Archaic)', 'v2t-s': 'Lower Nidan Verb (-tsu, Archaic)',
    'v2w-s': 'Lower Nidan Verb (-u, Archaic)', 'v2y-k': 'Upper Nidan Verb (-yu, Archaic)',
    'v2y-s': 'Lower Nidan Verb (-yu, Archaic)', 'v2z-s': 'Lower Nidan Verb (-zu, Archaic)'
  },
  fields: {
    Buddh: 'Buddhism', Christn: 'Christianity', MA: 'martial arts', Shinto: 'Shinto',
    agric: 'agriculture', anat: 'anatomy', archeol: 'archaeology', archit: 'architecture', art: 'art',
    astron: 'astronomy', audvid: 'audiovisual', aviat: 'aviation', baseb: 'baseball',
    biochem: 'biochemistry', biol: 'biology', bot: 'botany', boxing: 'boxing', bus: 'business',
    cards: 'card games', chem: 'chemistry', chmyth: 'Chinese mythology', civeng: 'civil engineering',
    cloth: 'clothing', comp: 'computing', cryst: 'crystallography', dent: 'dentistry', ecol: 'ecology',
    econ: 'economics', elec: 'electricity', electr: 'electronics', embryo: 'embryology',
    engr: 'engineering', ent: 'entomology', figskt: 'figure skating', film: 'film', finc: 'finance',
    fish: 'fishing', food: 'food', gardn: 'gardening', genet: 'genetics', geogr: 'geography',
    geol: 'geology', geom: 'geometry', go: 'go', golf: 'golf', gramm: 'grammar',
    grmyth: 'Greek mythology', hanaf: 'hanafuda', horse: 'horse racing', internet: 'internet',
    jpmyth: 'Japanese mythology', kabuki: 'kabuki', law: 'law', ling: 'linguistics', logic: 'logic',
    mahj: 'mahjong', manga: 'manga', math: 'mathematics', mech: 'mechanical engineering', med: 'medicine',
    met: 'meteorology', mil: 'military', min: 'mineralogy', mining: 'mining', motor: 'motorsport',
    music: 'music', noh: 'Noh', ornith: 'ornithology', paleo: 'paleontology', pathol: 'pathology',
    pharm: 'pharmacy', phil: 'philosophy', photo: 'photography', physics: 'physics',
    physiol: 'physiology', politics: 'politics', print: 'printing', prowres: 'professional wrestling',
    psy: 'psychiatry', psyanal: 'psychoanalysis', psych: 'psychology', rail: 'railways',
    rommyth: 'Roman mythology', shogi: 'shogi', ski: 'skiing', sports: 'sports', stat: 'statistics',
    stockm: 'stock market', sumo: 'sumo', surg: 'surgery', telec: 'telecommunications',
    tradem: 'trademark', tv: 'television', vet: 'veterinary medicine', vidg: 'video games', zool: 'zoology'
  },
  conjugations: {
    1: 'Non-past', 2: 'Past (~ta)', 3: 'Conjunctive (~te)', 4: 'Provisional (~eba)',
    5: 'Potential', 6: 'Passive', 7: 'Causative', 8: 'Causative-Passive', 9: 'Volitional',
    10: 'Imperative', 11: 'Conditional (~tara)', 12: 'Alternative (~tari)',
    13: 'Continuative (~i)', 50: 'Adverbial', 51: 'Adjective Stem', 52: 'Negative Stem',
    53: 'Causative (~su)', 54: 'Old/literary form'
  },
  suffixes: {
    chau: 'indicates completion (to finish ...)', ha: 'topic marker particle',
    tai: 'want to... / would like to...', iru: 'indicates continuing action (to be ...ing)',
    oru: 'indicates continuing action (to be ...ing) (humble)',
    aru: 'indicates completion / finished action',
    kuru: 'indicates action that had been continuing up till now / came to be',
    oku: 'to do in advance / to leave in the current state expecting a later change',
    kureru: '(asking) to do something for one', morau: '(asking) to get somebody to do something',
    itadaku: '(asking) to get somebody to do something (polite)',
    iku: 'is becoming / action starting now and continuing', suru: 'makes a verb from a noun',
    itasu: 'makes a verb from a noun (humble)',
    sareru: 'makes a verb from a noun (honorific or passive)',
    saseru: 'let/make someone/something do ...', rou: 'probably / it seems that... / I guess ...',
    ii: "it's ok if ... / is it ok if ...?", mo: 'even if ...', sugiru: 'to be too (much) ...',
    nikui: 'difficult to...', gatai: 'difficult to...', sa: '-ness (degree or condition of adjective)',
    tsutsu: 'while ... / in the process of ...',
    tsutsuaru: 'to be doing ... / to be in the process of doing ...',
    uru: 'can ... / to be able to ...', sou: 'looking like ... / seeming ...', nai: 'negative suffix',
    ra: 'pluralizing suffix (not polite)', kudasai: 'please do ...',
    yagaru: 'indicates disdain or contempt', naru: 'to become ...', desu: 'formal copula',
    desho: "it seems/perhaps/don't you think?", tosuru: 'to try to .../to be about to...',
    garu: 'to feel .../have a ... impression of someone', me: 'somewhat/-ish',
    gai: 'worth it to ...', tasou: 'seem to want to... (tai+sou)', 'polite-prefix': 'polite prefix',
    'particle-ni': 'at / in / by', 'particle-ka': 'or / questioning particle',
    'particle-e': 'to / at / in', 'particle-o': 'indicates direct object of action',
    'particle-no': "indicates possessive (...'s)", 'particle-to': 'quoting particle',
    'particle-kara': 'from / because'
  }
} as const satisfies PresentationCatalog;
