import type { PresentationCatalog } from '../schema.js';

export const ZH_HANS_CATALOG = {
  ui: {
    home: 'Ichiran 首页', settings: '分析器设置', analyzerData: '分析器数据',
    interfaceLanguage: '界面语言', onThisDevice: '本设备上占用 {size}', removeData: '移除数据',
    licenses: '许可证', installTitle: '安装日语数据',
    installIntro: '只需下载一次。分析时会直接读取本设备上的数据。', preparing: '正在准备分析器',
    staleData: '本地数据需要更新。', incompleteData: '保存的数据不完整，请重新安装。',
    insufficientStorage: '可用存储空间不足，无法安装分析器。', clearFailed: '无法移除保存的数据。',
    downloadFailed: '下载未完成。', downloading: '正在下载', checkingFiles: '正在检查文件',
    savingDevice: '正在保存到本设备', openingAnalyzer: '正在打开分析器', reinstall: '重新安装分析器数据',
    retry: '重试', install: '安装分析器数据', download: '下载大小', stored: '存储大小',
    byteProgress: '{received} / {total}',
    privacy: '你的文本始终保留在本设备上。', examples: '示例', trySentence: '试试这些句子',
    reading: '读音 {reading}', word: '词语', detailsFailed: '无法打开词语详情。',
    romanizationFailed: '无法生成罗马字。', replaceFailed: '新数据无法替换当前数据。',
    japaneseText: '日语文本', composerIntro: '粘贴句子或选择一个示例。', clearJapanese: '清除日语文本',
    analyzing: '分析中', analyze: '分析', analysisFailed: '分析失败。', tryAgain: '重试',
    analysisResult: '分析结果', analysis: '分析', definitions: '释义', english: '英语',
    simplifiedChinese: '简体中文', romanize: '显示罗马字', hideRomaji: '隐藏罗马字',
    otherParses: '其他分析', analyzeHint: '分析文本后即可查看每个词。', enterHint: '输入日语文本以开始。',
    wordDetails: '词语详情', close: '关闭', copyFailed: '无法复制所选内容。', runsOnDevice: '在本设备上运行',
    selectWord: '选择一个词', selectedText: '所选文本', copied: '已复制', copy: '复制',
    copySelected: '复制所选词语', closeDetails: '关闭词语详情', loadingDetails: '正在加载词语详情',
    negative: '否定', formal: '礼貌体', counter: '量词', ordinalCounter: '序数量词',
    properNoun: '专有名词', structure: '结构', conjugations: '活用', alternatives: '其他候选',
    unknownConjugation: '活用 {type}', confirmRemove: '要从本设备移除已下载的日语数据吗？',
    unsupportedTitle: '此浏览器无法在本地存储分析器。',
    unsupportedIntro: '请使用最新版浏览器，并关闭无痕浏览。', corruptData: '保存的数据已损坏。',
    reloadStatus: '请重新加载页面以检查保存的数据。'
  },
  samples: {
    everyday: '日常', inflection: '活用', counters: '量词', numbers: '数字', ambiguous: '多音词',
    mixedScripts: '混合文字', punctuation: '标点', colloquial: '口语', compound: '复合词', kana: '假名'
  },
  pos: {
    'adj-i': 'イ形容词', 'adj-ix': 'イ形容词（古语）', 'adj-na': 'ナ形容词',
    'adj-no': 'ノ形容词', 'adj-pn': '连体形容词', 'adj-t': 'タル形容词', 'adj-f': '连体词',
    adv: '副词', 'adv-to': 'ト副词', aux: '助词性成分', 'aux-v': '助动词',
    'aux-adj': '辅助形容词', conj: '接续词', cop: '系词', 'cop-da': '系词（だ）', ctr: '量词',
    exp: '惯用表达', int: '感叹词', n: '名词', 'n-adv': '副词性名词', 'n-suf': '名词后缀',
    'n-pref': '名词前缀', 'n-t': '时间名词', 'n-pr': '专有名词', num: '数词', pn: '代词',
    prt: '助词', pref: '前缀', suf: '后缀', v1: '一段动词（-ru）',
    'v1-s': '一段动词（-ru 特殊）', v5aru: '五段动词（-aru）', v5b: '五段动词（-bu）',
    v5g: '五段动词（-gu）', v5k: '五段动词（-ku）', 'v5k-s': '五段动词（-ku 特殊）',
    v5m: '五段动词（-mu）', v5n: '五段动词（-nu）', v5r: '五段动词（-ru）',
    'v5r-i': '五段动词（-ru 不规则）', v5s: '五段动词（-su）', v5t: '五段动词（-tsu）',
    v5u: '五段动词（-u）', 'v5u-s': '五段动词（-u 特殊）', vk: 'カ变动词', vs: 'サ变动词',
    'vs-i': 'サ变动词（内含）', 'vs-s': 'サ变动词（特殊）', vt: '及物动词', vi: '不及物动词',
    vz: 'ズル动词', v5uru: '五段动词（-uru）', 'on-mim': '拟声拟态词', unc: '未分类',
    'adj-kari': 'カリ形容词（古语）', 'adj-ku': 'ク形容词（古语）',
    'adj-shiku': 'シク形容词（古语）', 'adj-nari': 'ナリ形容词（古语）',
    'v-unspec': '动词（类型未指定）', vn: 'ヌ动词（不规则）', vr: 'ル动词（不规则）',
    'vs-c': 'ス动词（古语）', v4b: '四段动词（-bu，古语）', v4g: '四段动词（-gu，古语）',
    v4h: '四段动词（-fu，古语）', v4k: '四段动词（-ku，古语）',
    v4m: '四段动词（-mu，古语）', v4n: '四段动词（-nu，古语）',
    v4r: '四段动词（-ru，古语）', v4s: '四段动词（-su，古语）',
    v4t: '四段动词（-tsu，古语）', 'v2a-s': '二段动词（-u，古语）',
    'v2b-k': '上二段动词（-bu，古语）', 'v2b-s': '下二段动词（-bu，古语）',
    'v2d-k': '上二段动词（-dzu，古语）', 'v2d-s': '下二段动词（-dzu，古语）',
    'v2g-k': '上二段动词（-gu，古语）', 'v2g-s': '下二段动词（-gu，古语）',
    'v2h-k': '上二段动词（-fu，古语）', 'v2h-s': '下二段动词（-fu，古语）',
    'v2k-k': '上二段动词（-ku，古语）', 'v2k-s': '下二段动词（-ku，古语）',
    'v2m-k': '上二段动词（-mu，古语）', 'v2m-s': '下二段动词（-mu，古语）',
    'v2n-s': '下二段动词（-nu，古语）', 'v2r-k': '上二段动词（-ru，古语）',
    'v2r-s': '下二段动词（-ru，古语）', 'v2s-s': '下二段动词（-su，古语）',
    'v2t-k': '上二段动词（-tsu，古语）', 'v2t-s': '下二段动词（-tsu，古语）',
    'v2w-s': '下二段动词（-u，古语）', 'v2y-k': '上二段动词（-yu，古语）',
    'v2y-s': '下二段动词（-yu，古语）', 'v2z-s': '下二段动词（-zu，古语）'
  },
  fields: {
    Buddh: '佛教', Christn: '基督教', MA: '武术', Shinto: '神道教', agric: '农业', anat: '解剖学',
    archeol: '考古学', archit: '建筑学', art: '艺术', astron: '天文学', audvid: '视听技术',
    aviat: '航空', baseb: '棒球', biochem: '生物化学', biol: '生物学', bot: '植物学',
    boxing: '拳击', bus: '商业', cards: '纸牌游戏', chem: '化学', chmyth: '中国神话',
    civeng: '土木工程', cloth: '服装', comp: '计算机', cryst: '晶体学', dent: '牙科学',
    ecol: '生态学', econ: '经济学', elec: '电学', electr: '电子学', embryo: '胚胎学',
    engr: '工程学', ent: '昆虫学', figskt: '花样滑冰', film: '电影', finc: '金融', fish: '渔业',
    food: '饮食', gardn: '园艺', genet: '遗传学', geogr: '地理学', geol: '地质学', geom: '几何学',
    go: '围棋', golf: '高尔夫', gramm: '语法', grmyth: '希腊神话', hanaf: '花札', horse: '赛马',
    internet: '互联网', jpmyth: '日本神话', kabuki: '歌舞伎', law: '法律', ling: '语言学',
    logic: '逻辑学', mahj: '麻将', manga: '漫画', math: '数学', mech: '机械工程', med: '医学',
    met: '气象学', mil: '军事', min: '矿物学', mining: '采矿', motor: '赛车运动', music: '音乐',
    noh: '能乐', ornith: '鸟类学', paleo: '古生物学', pathol: '病理学', pharm: '药学',
    phil: '哲学', photo: '摄影', physics: '物理学', physiol: '生理学', politics: '政治',
    print: '印刷', prowres: '职业摔角', psy: '精神医学', psyanal: '精神分析', psych: '心理学',
    rail: '铁路', rommyth: '罗马神话', shogi: '将棋', ski: '滑雪', sports: '体育', stat: '统计学',
    stockm: '股票市场', sumo: '相扑', surg: '外科学', telec: '电信', tradem: '商标',
    tv: '电视', vet: '兽医学', vidg: '电子游戏', zool: '动物学'
  },
  conjugations: {
    1: '非过去式', 2: '过去式（～た）', 3: '接续形（～て）', 4: '假定形（～えば）',
    5: '可能形', 6: '被动形', 7: '使役形', 8: '使役被动形', 9: '意志形', 10: '命令形',
    11: '条件形（～たら）', 12: '列举形（～たり）', 13: '连用形（～い）', 50: '副词形',
    51: '形容词词干', 52: '否定词干', 53: '使役形（～す）', 54: '古语／书面语形式'
  },
  suffixes: {
    chau: '表示动作完成（做完……）', ha: '主题标记助词', tai: '想要……',
    iru: '表示动作持续（正在……）', oru: '表示动作持续（正在……，自谦）',
    aru: '表示动作已经完成', kuru: '表示动作持续至今，或逐渐变成某状态',
    oku: '预先做……；保持当前状态以备之后变化', kureru: '请对方为自己做……',
    morau: '请某人为自己做……', itadaku: '请某人为自己做……（礼貌）',
    iku: '逐渐变成……；从现在开始并持续', suru: '把名词变成动词',
    itasu: '把名词变成动词（自谦）', sareru: '把名词变成动词（尊敬或被动）',
    saseru: '让／使某人或某物做……', rou: '大概……／似乎……／我想……',
    ii: '……也可以／可以……吗？', mo: '即使……', sugiru: '过于……', nikui: '难以……',
    gatai: '难以……', sa: '表示形容词的程度或状态（……度／……性）',
    tsutsu: '一边……／正在……', tsutsuaru: '正在……／处于……的过程中', uru: '能够……',
    sou: '看起来……／似乎……', nai: '否定后缀', ra: '复数后缀（非礼貌）',
    kudasai: '请做……', yagaru: '表示轻蔑或不满', naru: '变成……', desu: '礼貌系词',
    desho: '似乎／也许／你不觉得吗？', tosuru: '试图……／正要……',
    garu: '表现出……的感受／给人……的印象', me: '有点……／偏……', gai: '值得……',
    tasou: '看起来想要……（たい＋そう）', 'polite-prefix': '礼貌前缀',
    'particle-ni': '在／于／以', 'particle-ka': '或者／疑问助词', 'particle-e': '向／到／在',
    'particle-o': '标记动作的直接宾语', 'particle-no': '表示所属关系（……的）',
    'particle-to': '引用助词', 'particle-kara': '从……／因为……'
  }
} as const satisfies PresentationCatalog;
