#!/usr/bin/env bun
/**
 * Generates authoritative GiNZA types purely from corpus-derived runtime values.
 * No training labels — only what GiNZA actually outputs.
 *
 * Output: src/ginza/generated.ts
 */

import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { GinzaClient } from '../src/ginza/client.ts';

const bunproDir = './data/bunpro';
const outputPath = './src/ginza/generated.ts';
const levels = ['JLPT5', 'JLPT4', 'JLPT3', 'JLPT2', 'JLPT1', 'Non-JLPT'];

// ─────────────────────────────────────────────────────────────────────────────
// 1. Collect sentences from Bunpro
// ─────────────────────────────────────────────────────────────────────────────
const sentences: string[] = [];
for (const level of levels) {
  const dir = join(bunproDir, level);
  try {
    for (const f of readdirSync(dir).filter((f) => f.endsWith('.json'))) {
      const raw = JSON.parse(readFileSync(join(dir, f), 'utf8'));
      for (const item of raw.included ?? []) {
        if (item?.type !== 'study_question') continue;
        const content = item?.attributes?.content ?? '';
        const answer = item?.attributes?.answer ?? '';
        if (content && answer) {
          const sentence = content
            .replace(/<[^>]+>/g, '')
            .replace(/（[^）]*）/g, '')
            .replaceAll('____', answer)
            .trim();
          if (sentence.length > 3) sentences.push(sentence);
        }
      }
    }
  } catch {}
}
console.error(`Loaded ${sentences.length} sentences from Bunpro`);

// ─────────────────────────────────────────────────────────────────────────────
// 2. Run GiNZA and collect actual runtime values
// ─────────────────────────────────────────────────────────────────────────────
const posLabels = new Set<string>();
const depLabels = new Set<string>();
const neLabels = new Set<string>();
const conjugationClasses = new Set<string>();
const inflectionForms = new Set<string>();
const batchSize = 128;

const client = new GinzaClient({ python: 'python3' });
await client.start();
const meta = await client.meta();

const start = Date.now();
try {
  for (let i = 0; i < sentences.length; i += batchSize) {
    const batch = sentences.slice(i, i + batchSize);
    const docs = await client.analyze(batch);
    for (const doc of docs) {
      for (const sent of doc.sentences) {
        for (const tok of sent.tokens) {
          if (tok.pos) posLabels.add(tok.pos);
          if (tok.dep) depLabels.add(tok.dep);
          if (tok.ne) neLabels.add(tok.ne);

          const inf = tok.inflection;
          if (inf) {
            const parts = inf.split(/[;,]/);
            if (parts[0]) conjugationClasses.add(parts[0].trim());
            if (parts[1]) inflectionForms.add(parts[1].trim());
          }
        }
      }
    }
    const done = Math.min(i + batchSize, sentences.length);
    const pct = ((done / sentences.length) * 100).toFixed(1);
    const elapsed = (Date.now() - start) / 1000;
    const rate = done / elapsed;
    const eta = ((sentences.length - done) / rate).toFixed(0);
    process.stderr.write(`\r[${pct}%] ${done}/${sentences.length} | ${rate.toFixed(0)} sent/s | ETA ${eta}s   `);
  }
  console.error('');
} finally {
  await client.stop();
}

// ─────────────────────────────────────────────────────────────────────────────
// 3. Sort all collected values
// ─────────────────────────────────────────────────────────────────────────────
const sortedPos = [...posLabels].filter(Boolean).sort();
const sortedDep = [...depLabels].filter(Boolean).sort();
const sortedNe = [...neLabels].filter(Boolean).sort();
const sortedConjClasses = [...conjugationClasses].filter(Boolean).sort();
const sortedInflForms = [...inflectionForms].filter(Boolean).sort();

// ─────────────────────────────────────────────────────────────────────────────
// 4. Generate TypeScript
// ─────────────────────────────────────────────────────────────────────────────
function toLiteralUnion(values: string[]): string {
  return values.map((v) => `'${v}'`).join(' | ');
}

function toZodEnum(values: string[]): string {
  return `z.enum([${values.map((v) => `'${v}'`).join(', ')}])`;
}

const code = `// AUTO-GENERATED by scripts/generate-ginza-types.ts — DO NOT EDIT
// Generated: ${new Date().toISOString()}
// Model: ${meta.model ?? 'unknown'} (spaCy ${meta.spacyVersion}, GiNZA ${meta.ginzaVersion})
// Corpus: ${sentences.length} Bunpro sentences (purely corpus-derived, no training labels)

import { z } from 'zod';

// ─────────────────────────────────────────────────────────────────────────────
// POS Labels (corpus-derived)
// ─────────────────────────────────────────────────────────────────────────────
export type GinzaPOS = ${toLiteralUnion(sortedPos)};
export const GinzaPOSSchema = ${toZodEnum(sortedPos)};
export const GINZA_POS_LABELS = [${sortedPos.map((v) => `'${v}'`).join(', ')}] as const;

// ─────────────────────────────────────────────────────────────────────────────
// Dependency Labels (corpus-derived)
// ─────────────────────────────────────────────────────────────────────────────
export type GinzaDep = ${toLiteralUnion(sortedDep)};
export const GinzaDepSchema = ${toZodEnum(sortedDep)};
export const GINZA_DEP_LABELS = [${sortedDep.map((v) => `'${v}'`).join(', ')}] as const;

// ─────────────────────────────────────────────────────────────────────────────
// NE Labels (corpus-derived)
// ─────────────────────────────────────────────────────────────────────────────
export type GinzaNE = ${sortedNe.length ? toLiteralUnion(sortedNe) : 'never'};
${sortedNe.length ? `export const GinzaNESchema = ${toZodEnum(sortedNe)};` : '// No NE labels found in corpus'}
${sortedNe.length ? `export const GINZA_NE_LABELS = [${sortedNe.map((v) => `'${v}'`).join(', ')}] as const;` : ''}

// ─────────────────────────────────────────────────────────────────────────────
// Bunsetsu Labels (static, well-known values)
// ─────────────────────────────────────────────────────────────────────────────
export type GinzaBunsetuBI = 'B' | 'I';
export const GinzaBunsetuBISchema = z.enum(['B', 'I']);

export type GinzaBunsetuPositionType = 'SEM_HEAD' | 'SYN_HEAD' | 'ROOT' | 'CONT' | 'NO_HEAD';
export const GinzaBunsetuPositionTypeSchema = z.enum(['SEM_HEAD', 'SYN_HEAD', 'ROOT', 'CONT', 'NO_HEAD']);

// ─────────────────────────────────────────────────────────────────────────────
// Conjugation Classes (corpus-derived from Inflection field)
// ─────────────────────────────────────────────────────────────────────────────
export type GinzaConjugationClass = ${toLiteralUnion(sortedConjClasses)};
export const GinzaConjugationClassSchema = ${toZodEnum(sortedConjClasses)};
export const GINZA_CONJUGATION_CLASSES = [${sortedConjClasses.map((v) => `'${v}'`).join(', ')}] as const;

// ─────────────────────────────────────────────────────────────────────────────
// Inflection Forms (corpus-derived from Inflection field)
// ─────────────────────────────────────────────────────────────────────────────
export type GinzaInflectionForm = ${toLiteralUnion(sortedInflForms)};
export const GinzaInflectionFormSchema = ${toZodEnum(sortedInflForms)};
export const GINZA_INFLECTION_FORMS = [${sortedInflForms.map((v) => `'${v}'`).join(', ')}] as const;

// ─────────────────────────────────────────────────────────────────────────────
// Helper: parse Inflection string into typed components
// ─────────────────────────────────────────────────────────────────────────────
export type ParsedInflection = {
  conjugationClass: GinzaConjugationClass | null;
  inflectionForm: GinzaInflectionForm | null;
  raw: string;
};

const CONJ_CLASS_SET = new Set<string>(GINZA_CONJUGATION_CLASSES);
const INFL_FORM_SET = new Set<string>(GINZA_INFLECTION_FORMS);

export function parseInflection(inf: string | undefined | null): ParsedInflection | null {
  if (!inf) return null;
  const parts = inf.split(/[;,]/);
  const cc = parts[0]?.trim() ?? '';
  const form = parts[1]?.trim() ?? '';
  return {
    conjugationClass: CONJ_CLASS_SET.has(cc) ? (cc as GinzaConjugationClass) : null,
    inflectionForm: INFL_FORM_SET.has(form) ? (form as GinzaInflectionForm) : null,
    raw: inf,
  };
}

export function hasInflectionForm(inf: string | undefined | null, form: GinzaInflectionForm): boolean {
  const parsed = parseInflection(inf);
  return parsed?.inflectionForm === form;
}

export function hasConjugationClass(inf: string | undefined | null, cc: GinzaConjugationClass): boolean {
  const parsed = parseInflection(inf);
  return parsed?.conjugationClass === cc;
}
`;

writeFileSync(outputPath, code);
console.log(`Generated ${outputPath}`);
console.log(`  POS: ${sortedPos.length}`);
console.log(`  Dep: ${sortedDep.length}`);
console.log(`  NE: ${sortedNe.length}`);
console.log(`  Conjugation classes: ${sortedConjClasses.length}`);
console.log(`  Inflection forms: ${sortedInflForms.length}`);
