// AUTO-GENERATED by scripts/generate-ginza-types.ts — DO NOT EDIT
// Generated: 2026-01-03T13:19:59.502Z
// Model: ginza (spaCy 3.8.11, GiNZA 5.2.0)
// Corpus: 15070 Bunpro sentences (purely corpus-derived, no training labels)

import { z } from 'zod';

// ─────────────────────────────────────────────────────────────────────────────
// POS Labels (corpus-derived)
// ─────────────────────────────────────────────────────────────────────────────
export type GinzaPOS = 'ADJ' | 'ADP' | 'ADV' | 'AUX' | 'CCONJ' | 'DET' | 'INTJ' | 'NOUN' | 'NUM' | 'PART' | 'PRON' | 'PROPN' | 'PUNCT' | 'SCONJ' | 'SYM' | 'VERB' | 'X';
export const GinzaPOSSchema = z.enum(['ADJ', 'ADP', 'ADV', 'AUX', 'CCONJ', 'DET', 'INTJ', 'NOUN', 'NUM', 'PART', 'PRON', 'PROPN', 'PUNCT', 'SCONJ', 'SYM', 'VERB', 'X']);
export const GINZA_POS_LABELS = ['ADJ', 'ADP', 'ADV', 'AUX', 'CCONJ', 'DET', 'INTJ', 'NOUN', 'NUM', 'PART', 'PRON', 'PROPN', 'PUNCT', 'SCONJ', 'SYM', 'VERB', 'X'] as const;

// ─────────────────────────────────────────────────────────────────────────────
// Dependency Labels (corpus-derived)
// ─────────────────────────────────────────────────────────────────────────────
export type GinzaDep = 'acl' | 'advcl' | 'advmod' | 'amod' | 'aux' | 'case' | 'cc' | 'ccomp' | 'compound' | 'cop' | 'csubj' | 'dep' | 'det' | 'discourse' | 'dislocated' | 'fixed' | 'mark' | 'nmod' | 'nsubj' | 'nummod' | 'obj' | 'obl' | 'punct' | 'root';
export const GinzaDepSchema = z.enum(['acl', 'advcl', 'advmod', 'amod', 'aux', 'case', 'cc', 'ccomp', 'compound', 'cop', 'csubj', 'dep', 'det', 'discourse', 'dislocated', 'fixed', 'mark', 'nmod', 'nsubj', 'nummod', 'obj', 'obl', 'punct', 'root']);
export const GINZA_DEP_LABELS = ['acl', 'advcl', 'advmod', 'amod', 'aux', 'case', 'cc', 'ccomp', 'compound', 'cop', 'csubj', 'dep', 'det', 'discourse', 'dislocated', 'fixed', 'mark', 'nmod', 'nsubj', 'nummod', 'obj', 'obl', 'punct', 'root'] as const;

// ─────────────────────────────────────────────────────────────────────────────
// NE Labels (corpus-derived)
// ─────────────────────────────────────────────────────────────────────────────
export type GinzaNE = 'B-DATE' | 'B-EVENT' | 'B-FAC' | 'B-GPE' | 'B-LANGUAGE' | 'B-LAW' | 'B-LOC' | 'B-MONEY' | 'B-NORP' | 'B-ORDINAL' | 'B-ORG' | 'B-OTHERS' | 'B-PERCENT' | 'B-PERSON' | 'B-PRODUCT' | 'B-QUANTITY' | 'B-TIME' | 'B-URL' | 'B-WORK_OF_ART' | 'I-DATE' | 'I-EVENT' | 'I-FAC' | 'I-GPE' | 'I-LANGUAGE' | 'I-LAW' | 'I-LOC' | 'I-MONEY' | 'I-NORP' | 'I-ORDINAL' | 'I-ORG' | 'I-OTHERS' | 'I-PERCENT' | 'I-PERSON' | 'I-PRODUCT' | 'I-QUANTITY' | 'I-TIME' | 'I-URL' | 'I-WORK_OF_ART' | 'O';
export const GinzaNESchema = z.enum(['B-DATE', 'B-EVENT', 'B-FAC', 'B-GPE', 'B-LANGUAGE', 'B-LAW', 'B-LOC', 'B-MONEY', 'B-NORP', 'B-ORDINAL', 'B-ORG', 'B-OTHERS', 'B-PERCENT', 'B-PERSON', 'B-PRODUCT', 'B-QUANTITY', 'B-TIME', 'B-URL', 'B-WORK_OF_ART', 'I-DATE', 'I-EVENT', 'I-FAC', 'I-GPE', 'I-LANGUAGE', 'I-LAW', 'I-LOC', 'I-MONEY', 'I-NORP', 'I-ORDINAL', 'I-ORG', 'I-OTHERS', 'I-PERCENT', 'I-PERSON', 'I-PRODUCT', 'I-QUANTITY', 'I-TIME', 'I-URL', 'I-WORK_OF_ART', 'O']);
export const GINZA_NE_LABELS = ['B-DATE', 'B-EVENT', 'B-FAC', 'B-GPE', 'B-LANGUAGE', 'B-LAW', 'B-LOC', 'B-MONEY', 'B-NORP', 'B-ORDINAL', 'B-ORG', 'B-OTHERS', 'B-PERCENT', 'B-PERSON', 'B-PRODUCT', 'B-QUANTITY', 'B-TIME', 'B-URL', 'B-WORK_OF_ART', 'I-DATE', 'I-EVENT', 'I-FAC', 'I-GPE', 'I-LANGUAGE', 'I-LAW', 'I-LOC', 'I-MONEY', 'I-NORP', 'I-ORDINAL', 'I-ORG', 'I-OTHERS', 'I-PERCENT', 'I-PERSON', 'I-PRODUCT', 'I-QUANTITY', 'I-TIME', 'I-URL', 'I-WORK_OF_ART', 'O'] as const;

// ─────────────────────────────────────────────────────────────────────────────
// Bunsetsu Labels (static, well-known values)
// ─────────────────────────────────────────────────────────────────────────────
export type GinzaBunsetuBI = 'B' | 'I';
export const GinzaBunsetuBISchema = z.enum(['B', 'I']);

export type GinzaBunsetuPositionType = 'SEM_HEAD' | 'SYN_HEAD' | 'ROOT' | 'CONT' | 'NO_HEAD';
export const GinzaBunsetuPositionTypeSchema = z.enum(['SEM_HEAD', 'SYN_HEAD', 'ROOT', 'CONT', 'NO_HEAD']);

// ─────────────────────────────────────────────────────────────────────────────
// Conjugation Classes (corpus-derived from Inflection field)
// ─────────────────────────────────────────────────────────────────────────────
export type GinzaConjugationClass = 'カ行変格' | 'サ行変格' | '上一段-ア行' | '上一段-カ行' | '上一段-ガ行' | '上一段-ザ行' | '上一段-タ行' | '上一段-ナ行' | '上一段-ハ行' | '上一段-バ行' | '上一段-マ行' | '上一段-ラ行' | '下一段-ア行' | '下一段-カ行' | '下一段-ガ行' | '下一段-サ行' | '下一段-タ行' | '下一段-ダ行' | '下一段-ナ行' | '下一段-ハ行' | '下一段-バ行' | '下一段-マ行' | '下一段-ラ行' | '五段-カ行' | '五段-ガ行' | '五段-サ行' | '五段-タ行' | '五段-ナ行' | '五段-バ行' | '五段-マ行' | '五段-ラ行' | '五段-ワア行' | '助動詞-ジャ' | '助動詞-タ' | '助動詞-タイ' | '助動詞-ダ' | '助動詞-デス' | '助動詞-ナイ' | '助動詞-ヌ' | '助動詞-マイ' | '助動詞-マス' | '助動詞-ヤ' | '助動詞-ラシイ' | '助動詞-レル' | '形容詞' | '文語サ行変格' | '文語ラ行変格' | '文語上二段-ダ行' | '文語下二段-ダ行' | '文語下二段-ラ行' | '文語助動詞-キ' | '文語助動詞-ゴトシ' | '文語助動詞-ジ' | '文語助動詞-ズ' | '文語助動詞-タリ-断定' | '文語助動詞-ナリ-断定' | '文語助動詞-ベシ' | '文語助動詞-マジ' | '文語助動詞-ム' | '文語助動詞-リ' | '文語四段-カ行' | '文語四段-ハ行' | '文語四段-ラ行' | '文語形容詞-ク' | '文語形容詞-シク';
export const GinzaConjugationClassSchema = z.enum(['カ行変格', 'サ行変格', '上一段-ア行', '上一段-カ行', '上一段-ガ行', '上一段-ザ行', '上一段-タ行', '上一段-ナ行', '上一段-ハ行', '上一段-バ行', '上一段-マ行', '上一段-ラ行', '下一段-ア行', '下一段-カ行', '下一段-ガ行', '下一段-サ行', '下一段-タ行', '下一段-ダ行', '下一段-ナ行', '下一段-ハ行', '下一段-バ行', '下一段-マ行', '下一段-ラ行', '五段-カ行', '五段-ガ行', '五段-サ行', '五段-タ行', '五段-ナ行', '五段-バ行', '五段-マ行', '五段-ラ行', '五段-ワア行', '助動詞-ジャ', '助動詞-タ', '助動詞-タイ', '助動詞-ダ', '助動詞-デス', '助動詞-ナイ', '助動詞-ヌ', '助動詞-マイ', '助動詞-マス', '助動詞-ヤ', '助動詞-ラシイ', '助動詞-レル', '形容詞', '文語サ行変格', '文語ラ行変格', '文語上二段-ダ行', '文語下二段-ダ行', '文語下二段-ラ行', '文語助動詞-キ', '文語助動詞-ゴトシ', '文語助動詞-ジ', '文語助動詞-ズ', '文語助動詞-タリ-断定', '文語助動詞-ナリ-断定', '文語助動詞-ベシ', '文語助動詞-マジ', '文語助動詞-ム', '文語助動詞-リ', '文語四段-カ行', '文語四段-ハ行', '文語四段-ラ行', '文語形容詞-ク', '文語形容詞-シク']);
export const GINZA_CONJUGATION_CLASSES = ['カ行変格', 'サ行変格', '上一段-ア行', '上一段-カ行', '上一段-ガ行', '上一段-ザ行', '上一段-タ行', '上一段-ナ行', '上一段-ハ行', '上一段-バ行', '上一段-マ行', '上一段-ラ行', '下一段-ア行', '下一段-カ行', '下一段-ガ行', '下一段-サ行', '下一段-タ行', '下一段-ダ行', '下一段-ナ行', '下一段-ハ行', '下一段-バ行', '下一段-マ行', '下一段-ラ行', '五段-カ行', '五段-ガ行', '五段-サ行', '五段-タ行', '五段-ナ行', '五段-バ行', '五段-マ行', '五段-ラ行', '五段-ワア行', '助動詞-ジャ', '助動詞-タ', '助動詞-タイ', '助動詞-ダ', '助動詞-デス', '助動詞-ナイ', '助動詞-ヌ', '助動詞-マイ', '助動詞-マス', '助動詞-ヤ', '助動詞-ラシイ', '助動詞-レル', '形容詞', '文語サ行変格', '文語ラ行変格', '文語上二段-ダ行', '文語下二段-ダ行', '文語下二段-ラ行', '文語助動詞-キ', '文語助動詞-ゴトシ', '文語助動詞-ジ', '文語助動詞-ズ', '文語助動詞-タリ-断定', '文語助動詞-ナリ-断定', '文語助動詞-ベシ', '文語助動詞-マジ', '文語助動詞-ム', '文語助動詞-リ', '文語四段-カ行', '文語四段-ハ行', '文語四段-ラ行', '文語形容詞-ク', '文語形容詞-シク'] as const;

// ─────────────────────────────────────────────────────────────────────────────
// Inflection Forms (corpus-derived from Inflection field)
// ─────────────────────────────────────────────────────────────────────────────
export type GinzaInflectionForm = '仮定形-一般' | '仮定形-融合' | '命令形' | '已然形-一般' | '意志推量形' | '未然形-サ' | '未然形-セ' | '未然形-一般' | '未然形-撥音便' | '未然形-補助' | '終止形-ウ音便' | '終止形-一般' | '終止形-撥音便' | '語幹-サ' | '語幹-一般' | '連体形-一般' | '連体形-撥音便' | '連体形-省略' | '連体形-補助' | '連用形-イ音便' | '連用形-ウ音便' | '連用形-ニ' | '連用形-一般' | '連用形-促音便' | '連用形-撥音便' | '連用形-融合';
export const GinzaInflectionFormSchema = z.enum(['仮定形-一般', '仮定形-融合', '命令形', '已然形-一般', '意志推量形', '未然形-サ', '未然形-セ', '未然形-一般', '未然形-撥音便', '未然形-補助', '終止形-ウ音便', '終止形-一般', '終止形-撥音便', '語幹-サ', '語幹-一般', '連体形-一般', '連体形-撥音便', '連体形-省略', '連体形-補助', '連用形-イ音便', '連用形-ウ音便', '連用形-ニ', '連用形-一般', '連用形-促音便', '連用形-撥音便', '連用形-融合']);
export const GINZA_INFLECTION_FORMS = ['仮定形-一般', '仮定形-融合', '命令形', '已然形-一般', '意志推量形', '未然形-サ', '未然形-セ', '未然形-一般', '未然形-撥音便', '未然形-補助', '終止形-ウ音便', '終止形-一般', '終止形-撥音便', '語幹-サ', '語幹-一般', '連体形-一般', '連体形-撥音便', '連体形-省略', '連体形-補助', '連用形-イ音便', '連用形-ウ音便', '連用形-ニ', '連用形-一般', '連用形-促音便', '連用形-撥音便', '連用形-融合'] as const;

// ─────────────────────────────────────────────────────────────────────────────
// Helper: parse Inflection string into typed components
// ─────────────────────────────────────────────────────────────────────────────
export type ParsedInflection = {
  conjugationClass: GinzaConjugationClass | null;
  inflectionForm: GinzaInflectionForm | null;
  raw: string;
};

const CONJ_CLASS_SET = new Set<string>(GINZA_CONJUGATION_CLASSES);
const INFL_FORM_SET = new Set<string>(GINZA_INFLECTION_FORMS);

export function parseInflection(inf: string | undefined | null): ParsedInflection | null {
  if (!inf) return null;
  const parts = inf.split(/[;,]/);
  const cc = parts[0]?.trim() ?? '';
  const form = parts[1]?.trim() ?? '';
  return {
    conjugationClass: CONJ_CLASS_SET.has(cc) ? (cc as GinzaConjugationClass) : null,
    inflectionForm: INFL_FORM_SET.has(form) ? (form as GinzaInflectionForm) : null,
    raw: inf,
  };
}

export function hasInflectionForm(inf: string | undefined | null, form: GinzaInflectionForm): boolean {
  const parsed = parseInflection(inf);
  return parsed?.inflectionForm === form;
}

export function hasConjugationClass(inf: string | undefined | null, cc: GinzaConjugationClass): boolean {
  const parsed = parseInflection(inf);
  return parsed?.conjugationClass === cc;
}
